# Generated by Django 4.1 on 2022-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_finches_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='finches',
            name='color',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
