# Generated by Django 4.1 on 2022-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_finches_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finches',
            name='color',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
    ]
