# Generated by Django 4.1 on 2022-08-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='finches',
            name='blade',
            field=models.ManyToManyField(to='main_app.blade'),
        ),
    ]
